### ISSUE TITLE
check_nonlinear uses packages not in require

### ISSUE THREAD

**Issue by atyre2** [atyre2/NRES803#9]
fix with usethis::use_package()

**Comment by disha4u** [comment]
Can I be assigned this issue

**Comment by atyre2** [comment]
@disha4u I use this package for teaching, so would prefer to let my students work on the issues if they want to. However, if you would like to try a fix, please fork the repository, make the change and create a pull request.

**Comment by atyre2** [comment]
fixed in bbbe95
